Endpoint: Generate a cart for the user
JoaoAugustoPansani/shopping-cart-test pull request #13
Opened 2022-05-02 16:52 UTC by JoaoAugustoPansani

Endpoint to generate cart for user when receive a session id token.

2022-05-02 18:24 UTC, wenderjean requested changes

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      id: {
Em regras gerais uma coluna `ID` sempre vai ser um Integer ou BigInteger incremental, salve quando você estiver usando UUIDs.

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      itemsId: {
Essa coluna me diz que um Cart tem apenas um item, ela é de  fato necessária?

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      voucher_code: {
Salvar o código do cupom é realmente necessário?

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      subtotal: {
Considerando que tu esta criando subtotal e total como inteiro, o que acha de adicionarmos um sufixo `_in_cents` em ambos?

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502181220-create-cart-item.js
> +      itemId: {
`itemId` parece redundante aqui, o que acha de mantermos `ID`? No geral todas as tabelas possuem um `ID` salvo tabelas de relacionamento "many to many"

2022-05-02 18:24 UTC, wenderjean commented on database/migrations/20220502181220-create-cart-item.js
> +    name: {
Os atributos `name ` e `price` são produto, aliás cada `cart_item` deveria se relacionar diretamente com um produto.

2022-05-02 18:24 UTC, wenderjean commented on database/seeders/20220502181043-demo-cart.js
> +'use strict';
Diferente do Produto, o Cart não é algo que tu precise criar previamente, é um dominio dinamico.

2022-05-02 18:24 UTC, wenderjean commented on src/controllers/cartController.js
> +      id: userSessionId,
Esse `session_id` não tem relação direta com o `ID` do cart apesar de que pode ser interessante uma coluna `user_session_id` no cart.

2022-05-02 18:24 UTC, wenderjean commented on src/models/Cart/Cart.js
> +  constraints: false
Seria interessante ter um constraint do ponto de vista da normalização de dados.

2022-05-02 18:24 UTC, wenderjean commented on src/models/Cart/Cart.js
> +CartItem.belongsTo(Cart)
Seria melhor mover essa linha para o `CartItem` em si.

2022-05-02 18:24 UTC, wenderjean commented on src/models/Cart/CartItem.js
> +const CartItem = sequelize.define(
Esse arquivo não me parece estar seguindo as especificações do code formatter.

2022-05-02 18:24 UTC, wenderjean commented on tests/requests/generateCartForUser.test.js
> +    it("should generate cart after receiving a user_session_id token", async () => {
Seria bom termos um teste exercitando o que acontece se o `user_session_id` não estiver presente.

2022-05-02 18:42 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      id: {
Id row datatype to INTEGER: DONE

2022-05-02 18:44 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      itemsId: {
Deleting unnecessary rows (1): DONE

2022-05-02 18:44 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      voucher_code: {
Deleting unnecessary rows (2): DONE

2022-05-02 18:47 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      subtotal: {
Adding _in_cents in price related rows: DONE

2022-05-02 18:49 UTC, JoaoAugustoPansani commented on database/migrations/20220502181220-create-cart-item.js
> +      itemId: {
Improving row name to id: DONE

2022-05-02 19:23 UTC, JoaoAugustoPansani commented on src/models/Cart/Cart.js
> +  constraints: false
Constraint to true: DONE

2022-05-02 19:37 UTC, JoaoAugustoPansani commented on database/seeders/20220502181043-demo-cart.js
> +'use strict';
Removing 'use strict' from cart and cart item migrations: DONE

2022-05-02 19:40 UTC, JoaoAugustoPansani commented on src/controllers/cartController.js
> +      id: userSessionId,
Adding a user_session_id row to cart table: DONE

2022-05-02 19:41 UTC, JoaoAugustoPansani commented on src/models/Cart/Cart.js
> +  constraints: false
Constraints to true: CAUSING ERROR('Error: carts.hasMany called with something that's not a subclass of Sequelize.Model')

2022-05-02 19:42 UTC, JoaoAugustoPansani commented on src/models/Cart/Cart.js
> +CartItem.belongsTo(Cart)
Moving .belongs to function into CartItem: DONE

2022-05-02 19:43 UTC, JoaoAugustoPansani commented on src/models/Cart/CartItem.js
> +const CartItem = sequelize.define(
Format all files: AFTER SOLVING ERRORS

2022-05-02 19:43 UTC, JoaoAugustoPansani commented on tests/requests/generateCartForUser.test.js
> +    it("should generate cart after receiving a user_session_id token", async () => {
Test for null user_session_id token: AFTER SOLVING ERRORS

2022-05-02 19:45 UTC, JoaoAugustoPansani commented on database/migrations/20220502181220-create-cart-item.js
> +    name: {
Creating an association between CartItem and Product: ERROR('Error: carts.hasOne called with something that's not a subclass of Sequelize.Model')

2022-05-02 20:23 UTC, JoaoAugustoPansani commented on database/migrations/20220502181220-create-cart-item.js
> +    name: {
UPDATE: ERROR FIXED

2022-05-02 20:23 UTC, JoaoAugustoPansani commented on src/models/Cart/Cart.js
> +  constraints: false
UPDATE: ERROR FIXED

2022-05-02 20:34 UTC, JoaoAugustoPansani commented on tests/requests/generateCartForUser.test.js
> +    it("should generate cart after receiving a user_session_id token", async () => {
UPDATE
Test for null user_session_id token: DONE

2022-05-04 12:17 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      id: {
What about auto-increment feature?

2022-05-04 12:21 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      user_session_id: {
What do you think about giving this column an index constraint considering we're going to use this value to search carts?

https://www.essentialsql.com/what-is-a-database-index/

2022-05-04 12:21 UTC, wenderjean commented on database/migrations/20220502181220-create-cart-item.js
> +      amount: {
Does this column apply for `_cents` logic?

2022-05-04 12:21 UTC, wenderjean commented on database/seeders/20220502181043-demo-cart.js
> +module.exports = {
We can get rid of this file.

2022-05-04 12:28 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      id: {
autoIncrement set to true at migrations: DONE

2022-05-04 12:32 UTC, JoaoAugustoPansani commented on database/migrations/20220502181220-create-cart-item.js
> +      amount: {
amount_in_cents for CartItem model: DONE

2022-05-04 12:35 UTC, wenderjean commented on database/migrations/20220502180555-create-cart.js
> +      id: {
It isn´t true :point_down:

2022-05-04 13:48 UTC, JoaoAugustoPansani commented on database/seeders/20220502181043-demo-cart.js
> +module.exports = {
DONE

2022-05-04 13:48 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      user_session_id: {
DONE

2022-05-04 13:49 UTC, JoaoAugustoPansani commented on database/migrations/20220502180555-create-cart.js
> +      id: {
Not pushed yet

2022-05-04 14:35 UTC, JoaoAugustoPansani commented
STATUS: CODE REWIED AND FORMATTED *WAITING APPROVAL*

2022-05-05 15:34 UTC, merged

2022-05-05 16:32 UTC, wenderjean commented
I asked changes in this PR so why it has been merged @JoaoAugustoPansani @tauantcamargo ?